name: rtw_cli
description: A CLI tool for generating Flutter components.
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  args: ^2.7.0
  path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  rtw: rtw_cli
